//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVGS
{
    using System;
    using System.Collections.Generic;
    
    public partial class creditInformation
    {
        public decimal cardNumber { get; set; }
        public string cardHolder { get; set; }
        public string cardType { get; set; }
        public string username { get; set; }
        public string expiryDate { get; set; }
        public decimal securityCode { get; set; }
    
        public virtual cardType cardType1 { get; set; }
        public virtual user user { get; set; }
    }
}
