//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVGS
{
    using System;
    using System.Collections.Generic;
    
    public partial class event_register
    {
        public decimal registerId { get; set; }
        public decimal eventId { get; set; }
        public string username { get; set; }
    
        public virtual eventData eventData { get; set; }
        public virtual login login { get; set; }
    }
}
