//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVGS
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.creditInformations = new HashSet<creditInformation>();
            this.eventDatas = new HashSet<eventData>();
            this.FriendsLists = new HashSet<FriendsList>();
            this.orders = new HashSet<order>();
            this.passResets = new HashSet<passReset>();
            this.wishLists = new HashSet<wishList>();
        }
    
        public string username { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string email { get; set; }
        public string mailAddress { get; set; }
        public string shipAddress { get; set; }
        public decimal age { get; set; }
        public Nullable<bool> employee { get; set; }
        public string favPlatform { get; set; }
        public string favPlatform2 { get; set; }
        public string favGenre { get; set; }
        public string favGenre2 { get; set; }
        public bool promoEmails { get; set; }
        public bool publicWishlist { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<creditInformation> creditInformations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eventData> eventDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FriendsList> FriendsLists { get; set; }
        public virtual genre genre { get; set; }
        public virtual genre genre1 { get; set; }
        public virtual login login { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order> orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<passReset> passResets { get; set; }
        public virtual platform platform { get; set; }
        public virtual platform platform1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wishList> wishLists { get; set; }
    }
}
